** Introducción a JavaScript

¡Hola! En este repositorio aprenderás mediante ejercicios las bases de JavaScript, el lenguaje más popular de la actualidad.

** ¿Qué es JavaScript?

*JavaScript es un lenguaje de programación
Creado originalmente para interactuar con elementos en una página web*

*No es Java.*
Es un derivado del lenguaje C.
Fue creado pensando en Java.

Se escribe y se compila dinámicamente JIT (Just in Time):

#+BEGIN_SRC
var x = 0;
El código se compila cuando se ejecuta
#+END_SRC

** Porque se llama Javascript?

- Inicialmente se llamaba "LiveScript".
- Fue construido en 10 días por [[https://es.wikipedia.org/wiki/Brendan_Eich][Brendan Eich]].
- Respaldado por SUN en 1995.

¡JavaScript está en todas partes!

- *Cliente:* La web ha evolucionado significativamente durante los ultimos 10 años, la cual es capaz de ejecutarse en diferentes entornos de desarrollo.

- *Servidor:* El runtime de Node.js que ejecuta JavaScript del lado del servidor.

- *Nativo:* Puede crear aplicaciones para escritorio, móviles como: React native, Electron y NativeScript.

** Fundamentos de Javascript

#+BEGIN_SRC
JavaScript en el navegador:

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Home Page</title>
</head>
<body>
	<button id="submit">Submit</button>
	<script>
		alert("Hello, JavaScript!");
	</script>
</body>
</html>
#+END_SRC

*** Marcado Moderno

#+BEGIN_SRC
El atributo type: <script type=“text/javascript”>
El atributo language: <script language=…>
#+END_SRC

*** Scripts externos

#+BEGIN_SRC
<script src=“/path/to/script.js”></script>
<script src=“https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.js”></script>
<script src=“/js/to/script1.js”></script>
<script src=“/js/to/script2.js”></script>
...
#+END_SRC

** Estructura del código

*** Sentencias

#+BEGIN_SRC
alert('Hola'); 
alert('Mundo');
#+END_SRC

*** Sin punto y coma

#+BEGIN_SRC
alert('Hola')
alert('Mundo')
#+END_SRC

*** Comentarios

#+BEGIN_SRC
// Este comentario ocupa una línea propia
alert('Hola');
alert('Mundo'); // Este comentario sigue a la sentencia
#+END_SRC

#+BEGIN_SRC
/* Este es un comentario multi línea */
#+END_SRC

** Declarando Variables

*** Dos maneras:

#+BEGIN_SRC
var uno;
let dos;
#+END_SRC

*** Nombramiento de variables

- El nombre únicamente puede incluir letras, dígitos, o los símbolos $ y _.
- El primer carácter no puede ser un dígito.

#+BEGIN_SRC
let userName;
let test123;
#+END_SRC

¿Cuándo debemos usarlo?

#+BEGIN_SRC
const por defecto
let en loops y valores cambiantes
#+END_SRC

** Tipos de Datos

*JavaScript tiene un tipado débil (no-tipados).*

- Tipos Simples del Lenguaje
Number (float), String, Boolean, Date, symbol, bigInt

- Tipos Especiales
NaN, null, undefined

- Estructuras de datos
Array y Object

*** Comprobando el tipo:

operador =typeof= devuelve una cadena del tipo de datos primitivo.

** Matemáticas en JavaScript

*** Matemáticas básicas

#+BEGIN_SRC
let num1 = 100;
console.log(num1 + 25);
console.log(num1 - 100);
console.log(num1 * 100);
console.log(num1 / 1500);
#+END_SRC

#+BEGIN_SRC
125
0
10000
0.06666666666666667
#+END_SRC

*** Operaciones matemáticas adicionales

#+BEGIN_SRC
let num1 = 100;
console.log(8 % 3); // Sobrante
console.log(++num1); // Incremento
console.log(--num1); // Decremento
#+END_SRC

#+BEGIN_SRC
2
101
99
#+END_SRC

*** El Objeto Math

Para operaciones matemáticas usando el objeto Math:

#+BEGIN_SRC
let num1 = 100;
console.log(Math.Pi); // Pi
console.log(Math.sqrt(num1)); // Raíz Cuadrada
#+END_SRC

#+BEGIN_SRC
3.141592653589793
10
#+END_SRC




