** Introducción a JavaScript

¡Hola! En este repositorio aprenderás mediante ejercicios las bases de JavaScript, el lenguaje más popular de la actualidad.

- [[file:./'Ejercicios Día 1'/][Ejercicios Día 1]]
- [[file:./'Ejercicios Día 2'/][Ejercicios Día 2]]
- [[file:./'Ejercicios Día 3'/][Ejercicios Día 3]]

** ¿Qué es JavaScript?

*JavaScript es un lenguaje de programación, creado originalmente para interactuar con elementos en una página web*

*No es Java.*
Es un derivado del lenguaje C.
Fue creado pensando en Java.

Se escribe y se compila dinámicamente JIT (Just in Time):

#+BEGIN_SRC
var x = 0;
El código se compila cuando se ejecuta
#+END_SRC

** Porque se llama Javascript?

- Inicialmente se llamaba "LiveScript".
- Fue construido en 10 días por [[https://es.wikipedia.org/wiki/Brendan_Eich][Brendan Eich]].
- Respaldado por SUN en 1995.

¡JavaScript está en todas partes!

- *Cliente:* La web ha evolucionado significativamente durante los ultimos 10 años, la cual es capaz de ejecutarse en diferentes entornos de desarrollo.

- *Servidor:* El runtime de Node.js que ejecuta JavaScript del lado del servidor.

- *Nativo:* Puede crear aplicaciones para escritorio, móviles como: React native, Electron y NativeScript.

** Fundamentos de Javascript

#+BEGIN_SRC
JavaScript en el navegador:

<!DOCTYPE html>
<html lang="en">
<head>
	<title>Home Page</title>
</head>
<body>
	<button id="submit">Submit</button>
	<script>
		alert("Hello, JavaScript!");
	</script>
</body>
</html>
#+END_SRC

*** Marcado Moderno

#+BEGIN_SRC
El atributo type: <script type=“text/javascript”>
El atributo language: <script language=…>
#+END_SRC

*** Scripts externos

#+BEGIN_SRC
<script src=“/path/to/script.js”></script>
<script src=“https://cdnjs.cloudflare.com/ajax/libs/lodash.js/4.17.11/lodash.js”></script>
<script src=“/js/to/script1.js”></script>
<script src=“/js/to/script2.js”></script>
...
#+END_SRC

** Estructura del código

*** Sentencias

#+BEGIN_SRC
alert('Hola'); 
alert('Mundo');
#+END_SRC

*** Sin punto y coma

#+BEGIN_SRC
alert('Hola')
alert('Mundo')
#+END_SRC

*** Comentarios

#+BEGIN_SRC
// Este comentario ocupa una línea propia
alert('Hola');
alert('Mundo'); // Este comentario sigue a la sentencia
#+END_SRC

#+BEGIN_SRC
/* Este es un comentario multi línea */
#+END_SRC

** Declarando Variables

*** Dos maneras:

#+BEGIN_SRC
var uno;
let dos;
#+END_SRC

*** Nombramiento de variables

- El nombre únicamente puede incluir letras, dígitos, o los símbolos $ y _.
- El primer carácter no puede ser un dígito.

#+BEGIN_SRC
let userName;
let test123;
#+END_SRC

¿Cuándo debemos usarlo?

#+BEGIN_SRC
const por defecto
let en loops y valores cambiantes
#+END_SRC

** Tipos de Datos

*JavaScript tiene un tipado débil (no-tipados).*

- Tipos Simples del Lenguaje
Number (float), String, Boolean, Date, symbol, bigInt

- Tipos Especiales
NaN, null, undefined

- Estructuras de datos
Array y Object

*** Comprobando el tipo:

operador =typeof= devuelve una cadena del tipo de datos primitivo.

** Matemáticas en JavaScript

*** Matemáticas básicas

#+BEGIN_SRC
let num1 = 100;

console.log(num1 + 25);
console.log(num1 - 100);
console.log(num1 * 100);
console.log(num1 / 1500);
#+END_SRC

#+BEGIN_SRC
125
0
10000
0.06666666666666667
#+END_SRC

*** Operaciones matemáticas adicionales

#+BEGIN_SRC
let num1 = 100;

console.log(8 % 3); // Sobrante
console.log(++num1); // Incremento
console.log(--num1); // Decremento
#+END_SRC

#+BEGIN_SRC
2
101
99
#+END_SRC

*** El Objeto Math

Para operaciones matemáticas usando el objeto Math:

#+BEGIN_SRC
let num1 = 100;

console.log(Math.Pi); // Pi
console.log(Math.sqrt(num1)); // Raíz Cuadrada
#+END_SRC

#+BEGIN_SRC
3.141592653589793
10
#+END_SRC

** Conversión entre números y cadenas

*** parseInt() y parseFloat()
- Convierte cadenas numéricas en números
- parseFloat() es para números de punto flotante, números con punto decimales

*** toString()
- Convierte números en cadenas numéricas

Conversión cadenas en enteros:

#+BEGIN_SRC
let num1 = '150';

console.log(parseInt('100'));
console.log(parseInt(num1));
console.log(parseInt('ABC'));
console.log(parseInt('0xF'));; // Número Hexadecimal
#+END_SRC

#+BEGIN_SRC
100
150
NaN
15
#+END_SRC

Conversión de cadenas en flotantes:

#+BEGIN_SRC
let flo1 = '1.50';

console.log(parseFloat('1.00'));
console.log(parseFloat(flo1));
console.log(parseFloat('ABC'));
#+END_SRC

#+BEGIN_SRC
1
1.5
NaN
#+END_SRC

Conversión de números en cadenas:

#+BEGIN_SRC
let num1 = 150;
let flo1 = 1.50;

console.log(num1.toString());
console.log(flo1.toString());
console.log((100).toString());
#+END_SRC

#+BEGIN_SRC
'150'
'1.50'
'100'
#+END_SRC

** Plantillas Literales

*** Formateo Flexible:
La sintaxis hace que las cadenas sean más fáciles de formatear y leer. Utilice marcadores de posición =$ {}= para variables o expresiones. Respeta los saltos de línea. No necesita el carácter de nueva línea "\ n“.

*** Utiliza comillas invertidas:
Las plantillas literales solo requieren el carácter de acento inverso =``= =(alt+96)=, colocado al principio y al final de una
cadena. No es necesario citar caracteres.

Concatenación con plantilla literales:

#+BEGIN_SRC
let str1 = "JavaScript";
let str2 = "fun";

console.log(`I am writing code in ${str1}`);
console.log(`Formatting strings in ${str1} is ${str2}!`);
#+END_SRC

#+BEGIN_SRC
I am writing code in JavaScript
Formatting strings in JavaScript is fun!
#+END_SRC

Expresiones en plantilla literales:

#+BEGIN_SRC
let bool1 = true;

console.log(`1 + 1 is ${1 + 1}`);
console.log(`The opposite of true is ${!bool1}`);
#+END_SRC

#+BEGIN_SRC
1 + 1 is 2
The opposite of true is false
#+END_SRC




